//! Bash script renderer

use crate::Manifest;

use super::Renderer;

/// Renders a manifest as an idempotent bash script
#[derive(Debug, Clone, Default)]
pub struct BashRenderer {
    /// Include progress output with machine-parseable markers
    pub verbose: bool,
    /// Use color output (ANSI escape codes)
    pub color: bool,
}

impl BashRenderer {
    /// Create a new bash renderer
    pub fn new() -> Self {
        Self {
            verbose: false,
            color: true,
        }
    }

    /// Enable verbose progress output
    pub fn verbose(mut self, verbose: bool) -> Self {
        self.verbose = verbose;
        self
    }

    /// Enable/disable color output
    pub fn color(mut self, color: bool) -> Self {
        self.color = color;
        self
    }
}

impl Renderer for BashRenderer {
    type Output = String;
    type Error = std::convert::Infallible;

    #[allow(clippy::too_many_lines)]
    fn render(&self, manifest: &Manifest) -> Result<String, Self::Error> {
        let mut script = String::new();

        script.push_str("#!/bin/bash\n");
        script.push_str("# Tengu PaaS Installation Script\n");
        script.push_str("# Generated by tengu-provision\n");
        script.push_str("# Idempotent - safe to re-run\n\n");
        script.push_str("set -euo pipefail\n\n");

        // Progress tracking functions with machine-parseable markers
        if self.verbose {
            if self.color {
                script.push_str(
                    r#"# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Progress markers for machine parsing
# Format: TENGU_STEP:ACTION:step_num:description
step_start() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:START:${step_num}:${desc}"
    echo -e "${BLUE}[$step_num]${NC} ${desc}..."
}

step_done() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:DONE:${step_num}:${desc}"
    echo -e "${GREEN}[$step_num]${NC} ${desc} ${GREEN}[done]${NC}"
}

step_skip() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:SKIP:${step_num}:${desc}"
    echo -e "${YELLOW}[$step_num]${NC} ${desc} ${YELLOW}[skipped]${NC}"
}

step_fail() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:FAIL:${step_num}:${desc}"
    echo -e "${RED}[$step_num]${NC} ${desc} ${RED}[FAILED]${NC}"
}

"#,
                );
            } else {
                script.push_str(
                    r#"# Progress markers for machine parsing (no color)
# Format: TENGU_STEP:ACTION:step_num:description
step_start() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:START:${step_num}:${desc}"
    echo "[$step_num] ${desc}..."
}

step_done() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:DONE:${step_num}:${desc}"
    echo "[$step_num] ${desc} [done]"
}

step_skip() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:SKIP:${step_num}:${desc}"
    echo "[$step_num] ${desc} [skipped]"
}

step_fail() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:FAIL:${step_num}:${desc}"
    echo "[$step_num] ${desc} [FAILED]"
}

"#,
                );
            }
        }

        let total_steps = manifest.steps.len();

        for (i, step) in manifest.steps.iter().enumerate() {
            let step_num = i + 1;
            let desc = step.description();
            // Escape description for use in shell strings
            let desc_escaped = desc.replace('"', "\\\"");

            if self.verbose {
                script.push_str(&format!("\n# Step {step_num}/{total_steps}: {desc}\n"));
            }

            // Wrap in idempotency check if available
            if let Some(check) = step.check_command() {
                script.push_str(&format!("if {check}; then\n"));
                if self.verbose {
                    script.push_str(&format!(
                        "    step_skip \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                script.push_str("else\n");
                if self.verbose {
                    script.push_str(&format!(
                        "    step_start \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                for cmd in step.to_bash() {
                    // Indent commands
                    for line in cmd.lines() {
                        script.push_str(&format!("    {line}\n"));
                    }
                }
                if self.verbose {
                    script.push_str(&format!(
                        "    step_done \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                script.push_str("fi\n");
            } else {
                if self.verbose {
                    script.push_str(&format!("step_start \"{step_num}\" \"{desc_escaped}\"\n"));
                }
                for cmd in step.to_bash() {
                    script.push_str(&format!("{cmd}\n"));
                }
                if self.verbose {
                    script.push_str(&format!("step_done \"{step_num}\" \"{desc_escaped}\"\n"));
                }
            }
        }

        if self.verbose {
            script.push_str(&format!(
                "\necho \"TENGU_STEP:COMPLETE:{total_steps}:all steps\"\n"
            ));
            if self.color {
                script.push_str("echo -e \"${GREEN}Tengu PaaS installation complete!${NC}\"\n");
            } else {
                script.push_str("echo 'Tengu PaaS installation complete!'\n");
            }
        } else {
            script.push_str("\necho 'Tengu PaaS installation complete!'\n");
        }

        Ok(script)
    }
}
