//! Bash script renderer

use crate::Manifest;

use super::Renderer;

/// Renders a manifest as an idempotent bash script
#[derive(Debug, Clone, Default)]
pub struct BashRenderer {
    /// Include progress output with machine-parseable markers
    pub verbose: bool,
    /// Use color output (ANSI escape codes)
    pub color: bool,
}

impl BashRenderer {
    /// Create a new bash renderer
    pub fn new() -> Self {
        Self {
            verbose: false,
            color: true,
        }
    }

    /// Enable verbose progress output
    pub fn verbose(mut self, verbose: bool) -> Self {
        self.verbose = verbose;
        self
    }

    /// Enable/disable color output
    pub fn color(mut self, color: bool) -> Self {
        self.color = color;
        self
    }
}

impl Renderer for BashRenderer {
    type Output = String;
    type Error = std::convert::Infallible;

    #[allow(clippy::too_many_lines)]
    fn render(&self, manifest: &Manifest) -> Result<String, Self::Error> {
        let mut script = String::new();

        script.push_str("#!/bin/bash\n");
        script.push_str("# Tengu PaaS Installation Script\n");
        script.push_str("# Generated by tengu-provision\n");
        script.push_str("# Idempotent - safe to re-run\n\n");
        script.push_str("set -uo pipefail\n");
        script.push_str("export DEBIAN_FRONTEND=noninteractive\n\n");

        // Kill unattended-upgrades and wait for apt locks
        // On fresh Ubuntu 24.04 VMs, unattended-upgrades runs immediately and holds
        // dpkg locks, causing every apt operation to fail with exit code 1/100.
        // Killing it and waiting for the lock to release prevents cascading failures.
        script.push_str(
            "# Kill unattended-upgrades and wait for apt locks\n\
             systemctl stop unattended-upgrades 2>/dev/null || true\n\
             systemctl disable unattended-upgrades 2>/dev/null || true\n\
             killall -9 unattended-upgrade 2>/dev/null || true\n\
             while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do\n\
             \x20   echo \"Waiting for dpkg lock...\"\n\
             \x20   sleep 5\n\
             done\n\
             dpkg --configure -a 2>/dev/null || true\n\n",
        );

        // Progress tracking functions with machine-parseable markers
        if self.verbose {
            if self.color {
                script.push_str(
                    r#"# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Track installed packages for clean uninstall
TENGU_INSTALLED_FILE="/etc/tengu/installed-by-tengu.txt"
track_pkg() {
    local pkg="$1"
    mkdir -p /etc/tengu
    if ! grep -qxF "$pkg" "$TENGU_INSTALLED_FILE" 2>/dev/null; then
        echo "$pkg" >> "$TENGU_INSTALLED_FILE"
    fi
}

# Progress markers for machine parsing
# Format: TENGU_STEP:ACTION:step_num:description
step_start() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:START:${step_num}:${desc}"
    echo -e "${BLUE}[$step_num]${NC} ${desc}..."
}

step_done() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:DONE:${step_num}:${desc}"
    echo -e "${GREEN}[$step_num]${NC} ${desc} ${GREEN}[done]${NC}"
}

step_skip() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:SKIP:${step_num}:${desc}"
    echo -e "${YELLOW}[$step_num]${NC} ${desc} ${YELLOW}[skipped]${NC}"
}

step_fail() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:FAIL:${step_num}:${desc}"
    echo -e "${RED}[$step_num]${NC} ${desc} ${RED}[FAILED]${NC}"
}

"#,
                );
            } else {
                script.push_str(
                    r#"# Track installed packages for clean uninstall
TENGU_INSTALLED_FILE="/etc/tengu/installed-by-tengu.txt"
track_pkg() {
    local pkg="$1"
    mkdir -p /etc/tengu
    if ! grep -qxF "$pkg" "$TENGU_INSTALLED_FILE" 2>/dev/null; then
        echo "$pkg" >> "$TENGU_INSTALLED_FILE"
    fi
}

# Progress markers for machine parsing (no color)
# Format: TENGU_STEP:ACTION:step_num:description
step_start() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:START:${step_num}:${desc}"
    echo "[$step_num] ${desc}..."
}

step_done() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:DONE:${step_num}:${desc}"
    echo "[$step_num] ${desc} [done]"
}

step_skip() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:SKIP:${step_num}:${desc}"
    echo "[$step_num] ${desc} [skipped]"
}

step_fail() {
    local step_num="$1"
    local desc="$2"
    echo "TENGU_STEP:FAIL:${step_num}:${desc}"
    echo "[$step_num] ${desc} [FAILED]"
}

"#,
                );
            }
        }

        let total_steps = manifest.steps.len();

        for (i, step) in manifest.steps.iter().enumerate() {
            let step_num = i + 1;
            let desc = step.description();
            // Escape description for use in shell strings
            let desc_escaped = desc.replace('"', "\\\"");

            if self.verbose {
                script.push_str(&format!("\n# Step {step_num}/{total_steps}: {desc}\n"));
            }

            // Wrap in idempotency check if available
            // Use subshell for check to isolate from set -e + pipefail interaction
            if let Some(check) = step.check_command() {
                script.push_str(&format!("if (set +e; {check}); then\n"));
                if self.verbose {
                    script.push_str(&format!(
                        "    step_skip \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                script.push_str("else\n");
                if self.verbose {
                    script.push_str(&format!(
                        "    step_start \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                for cmd in step.to_bash() {
                    // Indent commands
                    for line in cmd.lines() {
                        script.push_str(&format!("    {line}\n"));
                    }
                }
                if self.verbose {
                    script.push_str(&format!(
                        "    step_done \"{step_num}\" \"{desc_escaped}\"\n"
                    ));
                }
                script.push_str("fi\n");
            } else {
                if self.verbose {
                    script.push_str(&format!("step_start \"{step_num}\" \"{desc_escaped}\"\n"));
                }
                for cmd in step.to_bash() {
                    script.push_str(&format!("{cmd}\n"));
                }
                if self.verbose {
                    script.push_str(&format!("step_done \"{step_num}\" \"{desc_escaped}\"\n"));
                }
            }
        }

        // Final verification — check critical services are running
        // Without set -e, errors are non-fatal, so we verify at the end
        script.push_str(
            "\n# Final verification of critical services\n\
             FAIL=0\n\
             for svc in docker postgresql caddy; do\n\
             \x20   if ! systemctl is-active --quiet $svc 2>/dev/null; then\n\
             \x20       echo \"FATAL: $svc is not running\"\n\
             \x20       FAIL=1\n\
             \x20   fi\n\
             done\n\
             if [ \"$FAIL\" -ne 0 ]; then\n\
             \x20   echo \"Critical service check failed\"\n\
             \x20   exit 1\n\
             fi\n\n",
        );

        if self.verbose {
            script.push_str(&format!(
                "echo \"TENGU_STEP:COMPLETE:{total_steps}:all steps\"\n"
            ));
            if self.color {
                script.push_str("echo -e \"${GREEN}Tengu PaaS installation complete!${NC}\"\n");
            } else {
                script.push_str("echo 'Tengu PaaS installation complete!'\n");
            }
        } else {
            script.push_str("echo 'Tengu PaaS installation complete!'\n");
        }

        Ok(script)
    }
}
